version: '3'
services:
  mariadb:
    container_name: mariadb_con
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb_vol:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped
  nginx:
    container_name: nginx_con
    build:
      context: requirements/nginx
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wordpress_vol:/var/www/wordpress
    restart: unless-stopped
volumes:
    wordpress_vol:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: '/home/jaewkim/data/wordpress'
    mariadb_vol:
      driver: local
      driver_opts:
        device: /home/jaewkim/data/wordpress
        o: bind
        type: none
networks:
    inception:
      driver: bridge
