version: '3'
services:
  mariadb:
    container_name: mariadb_con
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb_vol:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped
  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress_con
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress_vol:/var/www/wordpress
    networks:
      - inception
    restart: unless-stopped
  nginx:
    depends_on:
      - wordpress
    container_name: nginx_con
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 443:443
    volumes:
      - wordpress_vol:/var/www/wordpress
    networks:
      - inception
    restart: on-failure
volumes:
    wordpress_vol:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: '/home/jaewkim/data/wordpress'
    mariadb_vol:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: '/home/jaewkim/data/mariadb'

networks:
    inception:
      driver: bridge
