version: '3'

services:

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - app-network

  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - wp:/var/www/html
    expose:
      - "9000"
    networks:
      - app-network

  nginx:
    depends_on:
      - wordpress
    build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/html
    networks:
      - app-network

volumes:
  dbdata:
    driver: local
    driver_opts: # dbdata에 대한 옵션
      o: bind # 내가 지정한 로컬 경로와 도커 내의 실제 볼륨을 연동시켜 주겠다.
      type: volume # 타입이 두가지 있다. 바인드 머시기랑 볼륨 있다.
      device: /home/dcho/data/dbdata
  wp:
    driver: local
    driver_opts: # wp 대한 옵션
      o: bind # 내가 지정한 로컬 경로와 도커 내의 실제 볼륨을 연동시켜 주겠다.
      type: volume # 타입이 두가지 있다. 바인드 머시기랑 볼륨 있다.
      device: /home/dcho/data/wp


networks:
  app-network:
    driver: bridge
