FROM	debian:buster

RUN		apt-get -y update &&\
		apt-get -y upgrade
RUN		apt-get -y install nginx\
		openssl

# ssl 인증서 발급 후 nginx에서 사용할 수 있게 권한을 777로 설정
RUN		openssl req -newkey rsa:4096 -days 365 -nodes -x509\
		-subj "/C=KR/ST=Seoul/L=Seoul/O=42Seoul/OU=42/CN=localhost"\
		-keyout /etc/ssl/private/localhost_p.key\
		-out /etc/ssl/certs/localhost.crt &&\
		chmod 777 /etc/ssl/certs/localhost.crt /etc/ssl/private/localhost_p.key

# nginx config file 복사
COPY	./conf/default	/etc/nginx/sites-available/default

# nginx를 foreground로 실행
CMD		["nginx", "-g", "daemon off;"]
