version : '3'

services:
        mariadb:
                build: ./requirements/mariadb
                restart: on-failure
                expose:
                        - 3306
                networks:
                        - Inception
                volumes:
                        - mariadb:/var/lib/mysql
                env_file:
                        - .env

        wordpress:
                build: ./requirements/wordpress
                restart: on-failure
                expose:
                        - 9000
                networks:
                        - Inception
                volumes:
                        - wordpress:/var/www/wordpress
                env_file:
                        - .env
                depends_on:
                        - mariadb

        nginx:
                build: ./requirements/nginx
                restart: on-failure
                ports:
                        - 443:443
                networks:
                        - Inception
                volumes:
                        - wordpress:/var/www/wordpress
                depends_on:
                        - wordpress

networks:
        Inception:
                driver: bridge

volumes:
        wordpress:
                name: wordpress
                driver_opts:
                        device: /home/seungoh/data/wordpress
                        o: bind
                        type: none
        mariadb:
                name: mariadb
                driver_opts:
                        device: /home/seungoh/data/mariadb
                        o: bind
                        type: none

# 만약 mount error나면 파일을 생성해주고 다시 돌리기

# docker run -i
# stdin_open: true
# docker run -t
# tty: true
