version: '3'
services:
    mariadb:
        container_name: mariadb_con
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        networks:
            - inception
        env_file:
            - .env
        volumes:
            - mariadb_vol:/var/lib/mysql/
        restart: unless-stopped
    wordpress:
        depends_on:
            - mariadb
        build:
            context: requirements/wordpress
            dockerfile: Dockerfile
        container_name: wordpress_con
        networks:
            - inception
        env_file:
            - .env
        volumes:
            - wordpress_vol:/var/www/wordpress
        restart: unless-stopped
    nginx:
        depends_on:
            - wordpress
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        container_name: nginx_con
        networks:
            - inception
        env_file:
            - .env
        ports: 
            - "443:443"
        volumes:
            - wordpress_vol:/var/www/wordpress
        restart: unless-stopped
volumes:
    wordpress_vol:
        driver: local
        driver_opts:
            type: volume
            o: bind
            device: /home/jay/data/wordpress
    mariadb_vol:
        driver: local
        driver_opts:
            type: volume
            o: bind
            device: /home/jay/data/mariadb
networks:
    inception:
        driver: bridge

